version: '3'
services:
  my-etcd:
    image: quay.io/coreos/etcd
    command: ["/usr/local/bin/etcd", "--name", "my-etcd", "--advertise-client-urls", "http://0.0.0.0:2379", "--listen-client-urls", "http://0.0.0.0:2379", "--initial-advertise-peer-urls", "http://0.0.0.0:2380", "--listen-peer-urls", "http://0.0.0.0:2380", "--initial-cluster", "my-etcd=http://0.0.0.0:2380"]
    networks:
      - microservices-tutorial
    ports:
      - "2379:2379"
      - "2380:2380"

  my-prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus-config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - microservices-tutorial
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  my-jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"  # Jaeger Web UI 端口
      - "4317:4317"  # Jaeger Agent HTTP端口
      - "14268:14268"  # Jaeger Agent gRPC端口
      - "6831:6831/udp"  # Jaeger Agent UDP端口
    networks:
      - microservices-tutorial
    environment:
      - LOG_LEVEL=debug

  add-grpc-service:
    image: add-grpc-service:latest
    ports:
      - "18080:18080"
      - "18002:8002"
    networks:
      - microservices-tutorial
    depends_on:
      - my-etcd
      - my-prometheus

  sub-grpc-service:
    image: sub-grpc-service:latest
    ports:
      - "18081:18081"
      - "18003:8003"
    networks:
      - microservices-tutorial
    depends_on:
      - my-etcd
      - my-prometheus

networks:
  microservices-tutorial: