// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.0--rc1
// source: mul.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MulRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A int64 `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
}

func (x *MulRequest) Reset() {
	*x = MulRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mul_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MulRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MulRequest) ProtoMessage() {}

func (x *MulRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mul_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MulRequest.ProtoReflect.Descriptor instead.
func (*MulRequest) Descriptor() ([]byte, []int) {
	return file_mul_proto_rawDescGZIP(), []int{0}
}

func (x *MulRequest) GetA() int64 {
	if x != nil {
		return x.A
	}
	return 0
}

type MulResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	V int64 `protobuf:"varint,1,opt,name=v,proto3" json:"v,omitempty"`
}

func (x *MulResponse) Reset() {
	*x = MulResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mul_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MulResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MulResponse) ProtoMessage() {}

func (x *MulResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mul_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MulResponse.ProtoReflect.Descriptor instead.
func (*MulResponse) Descriptor() ([]byte, []int) {
	return file_mul_proto_rawDescGZIP(), []int{1}
}

func (x *MulResponse) GetV() int64 {
	if x != nil {
		return x.V
	}
	return 0
}

var File_mul_proto protoreflect.FileDescriptor

var file_mul_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6d, 0x75, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22,
	0x1a, 0x0a, 0x0a, 0x4d, 0x75, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a,
	0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x61, 0x22, 0x1b, 0x0a, 0x0b, 0x4d,
	0x75, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x76, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x76, 0x32, 0x36, 0x0a, 0x0a, 0x4d, 0x75, 0x6c, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x28, 0x0a, 0x03, 0x4d, 0x75, 0x6c, 0x12, 0x0e, 0x2e,
	0x70, 0x62, 0x2e, 0x4d, 0x75, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e,
	0x70, 0x62, 0x2e, 0x4d, 0x75, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_mul_proto_rawDescOnce sync.Once
	file_mul_proto_rawDescData = file_mul_proto_rawDesc
)

func file_mul_proto_rawDescGZIP() []byte {
	file_mul_proto_rawDescOnce.Do(func() {
		file_mul_proto_rawDescData = protoimpl.X.CompressGZIP(file_mul_proto_rawDescData)
	})
	return file_mul_proto_rawDescData
}

var file_mul_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mul_proto_goTypes = []interface{}{
	(*MulRequest)(nil),  // 0: pb.MulRequest
	(*MulResponse)(nil), // 1: pb.MulResponse
}
var file_mul_proto_depIdxs = []int32{
	0, // 0: pb.MulService.Mul:input_type -> pb.MulRequest
	1, // 1: pb.MulService.Mul:output_type -> pb.MulResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mul_proto_init() }
func file_mul_proto_init() {
	if File_mul_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mul_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MulRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mul_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MulResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mul_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mul_proto_goTypes,
		DependencyIndexes: file_mul_proto_depIdxs,
		MessageInfos:      file_mul_proto_msgTypes,
	}.Build()
	File_mul_proto = out.File
	file_mul_proto_rawDesc = nil
	file_mul_proto_goTypes = nil
	file_mul_proto_depIdxs = nil
}
