// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.0--rc1
// source: mul.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MulService_Mul_FullMethodName = "/pb.MulService/Mul"
)

// MulServiceClient is the client API for MulService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MulServiceClient interface {
	Mul(ctx context.Context, in *MulRequest, opts ...grpc.CallOption) (*MulResponse, error)
}

type mulServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMulServiceClient(cc grpc.ClientConnInterface) MulServiceClient {
	return &mulServiceClient{cc}
}

func (c *mulServiceClient) Mul(ctx context.Context, in *MulRequest, opts ...grpc.CallOption) (*MulResponse, error) {
	out := new(MulResponse)
	err := c.cc.Invoke(ctx, MulService_Mul_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MulServiceServer is the server API for MulService service.
// All implementations should embed UnimplementedMulServiceServer
// for forward compatibility
type MulServiceServer interface {
	Mul(context.Context, *MulRequest) (*MulResponse, error)
}

// UnimplementedMulServiceServer should be embedded to have forward compatible implementations.
type UnimplementedMulServiceServer struct {
}

func (UnimplementedMulServiceServer) Mul(context.Context, *MulRequest) (*MulResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Mul not implemented")
}

// UnsafeMulServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MulServiceServer will
// result in compilation errors.
type UnsafeMulServiceServer interface {
	mustEmbedUnimplementedMulServiceServer()
}

func RegisterMulServiceServer(s grpc.ServiceRegistrar, srv MulServiceServer) {
	s.RegisterService(&MulService_ServiceDesc, srv)
}

func _MulService_Mul_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MulRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MulServiceServer).Mul(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MulService_Mul_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MulServiceServer).Mul(ctx, req.(*MulRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MulService_ServiceDesc is the grpc.ServiceDesc for MulService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MulService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.MulService",
	HandlerType: (*MulServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Mul",
			Handler:    _MulService_Mul_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mul.proto",
}
