// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/add.proto

package add

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Add service

func NewAddEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Add service

type AddService interface {
	Add(ctx context.Context, in *AddRequest, opts ...client.CallOption) (*AddResponse, error)
}

type addService struct {
	c    client.Client
	name string
}

func NewAddService(name string, c client.Client) AddService {
	return &addService{
		c:    c,
		name: name,
	}
}

func (c *addService) Add(ctx context.Context, in *AddRequest, opts ...client.CallOption) (*AddResponse, error) {
	req := c.c.NewRequest(c.name, "Add.Add", in)
	out := new(AddResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Add service

type AddHandler interface {
	Add(context.Context, *AddRequest, *AddResponse) error
}

func RegisterAddHandler(s server.Server, hdlr AddHandler, opts ...server.HandlerOption) error {
	type add interface {
		Add(ctx context.Context, in *AddRequest, out *AddResponse) error
	}
	type Add struct {
		add
	}
	h := &addHandler{hdlr}
	return s.Handle(s.NewHandler(&Add{h}, opts...))
}

type addHandler struct {
	AddHandler
}

func (h *addHandler) Add(ctx context.Context, in *AddRequest, out *AddResponse) error {
	return h.AddHandler.Add(ctx, in, out)
}
