// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/mul.proto

package mul

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Mul service

func NewMulEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Mul service

type MulService interface {
	Mul(ctx context.Context, in *MulRequest, opts ...client.CallOption) (*MulResponse, error)
}

type mulService struct {
	c    client.Client
	name string
}

func NewMulService(name string, c client.Client) MulService {
	return &mulService{
		c:    c,
		name: name,
	}
}

func (c *mulService) Mul(ctx context.Context, in *MulRequest, opts ...client.CallOption) (*MulResponse, error) {
	req := c.c.NewRequest(c.name, "Mul.Mul", in)
	out := new(MulResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Mul service

type MulHandler interface {
	Mul(context.Context, *MulRequest, *MulResponse) error
}

func RegisterMulHandler(s server.Server, hdlr MulHandler, opts ...server.HandlerOption) error {
	type mul interface {
		Mul(ctx context.Context, in *MulRequest, out *MulResponse) error
	}
	type Mul struct {
		mul
	}
	h := &mulHandler{hdlr}
	return s.Handle(s.NewHandler(&Mul{h}, opts...))
}

type mulHandler struct {
	MulHandler
}

func (h *mulHandler) Mul(ctx context.Context, in *MulRequest, out *MulResponse) error {
	return h.MulHandler.Mul(ctx, in, out)
}
