// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/sub.proto

package sub

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Sub service

func NewSubEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Sub service

type SubService interface {
	Sub(ctx context.Context, in *SubRequest, opts ...client.CallOption) (*SubResponse, error)
}

type subService struct {
	c    client.Client
	name string
}

func NewSubService(name string, c client.Client) SubService {
	return &subService{
		c:    c,
		name: name,
	}
}

func (c *subService) Sub(ctx context.Context, in *SubRequest, opts ...client.CallOption) (*SubResponse, error) {
	req := c.c.NewRequest(c.name, "Sub.Sub", in)
	out := new(SubResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Sub service

type SubHandler interface {
	Sub(context.Context, *SubRequest, *SubResponse) error
}

func RegisterSubHandler(s server.Server, hdlr SubHandler, opts ...server.HandlerOption) error {
	type sub interface {
		Sub(ctx context.Context, in *SubRequest, out *SubResponse) error
	}
	type Sub struct {
		sub
	}
	h := &subHandler{hdlr}
	return s.Handle(s.NewHandler(&Sub{h}, opts...))
}

type subHandler struct {
	SubHandler
}

func (h *subHandler) Sub(ctx context.Context, in *SubRequest, out *SubResponse) error {
	return h.SubHandler.Sub(ctx, in, out)
}
